service: el-backend
useDotenv: true
plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-offline
custom:
  warmup:
    - production
    - staging
package:
  excludeDevDependencies: false
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    TMDB_ACCESS_TOKEN: ${env:TMDB_ACCESS_TOKEN}
    TMDB_API_BASE_URL: ${env:TMDB_API_BASE_URL}
    MONGODB_URI: ${env:MONGODB_URI}
    AWS_COGNITO_USER_POOL_ID: ${env:AWS_COGNITO_USER_POOL_ID}
    AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
    AWS_COGNITO_AUTHORITY: ${env:AWS_COGNITO_AUTHORITY}
functions:
  el-backend:
    handler: dist/serverless.handler
    name: ${sls:stage}-el-backend
    description: Movie notes and favorites management
    url: true
    events:
      - httpApi: 'GET /movies/search'
      - httpApi: 'GET /movies/popular'
      - httpApi: 'POST /auth/register'
      - httpApi: 'POST /auth/login'
      - httpApi: 'POST /users/favorites'
      - httpApi: 'POST /users/notes'
      - httpApi: 'PATCH /users/notes/{nodeId}'
